---
image: docker:stable-dind

services:
  - docker:dind

before_script:
  - apk add --no-cache
    python3 python3-dev py3-pip gcc git curl build-base
    autoconf automake py3-cryptography linux-headers
    musl-dev libffi-dev openssl-dev openssh
  - docker info
  - python3 --version
  - python3 -m pip install ansible==2.10.6
  - python3 -m pip install molecule==3.3.2
  - python3 -m pip install molecule-docker==0.2.4
  - python3 -m pip install yamllint==1.26.1
  - python3 -m pip install ansible-lint==5.0.10

molecule:
  stage: test
  script:
    - molecule test
